---
title: "Research and professional experience"
---

## 4. PhD: Water Quality Modeling (Department of Biological & Agricultural Engineering - North Carolina State University)

Dissertation Title: *Phosphorus Dynamics in Agricultural Systems: Source apportionment, sensitivity, and management evaluation using process-based modeling*

### Project 1: Phosphorus Source Apportionment in SWAT

Identifying the contributions of different phosphorus (P) sources is essential for improving water quality in agricultural watersheds. This project applies the Soil and Water Assessment Tool (SWAT) to quantify and compare P inputs from major land-based sources—including fertilizer, manure, and soil erosion—and to determine their relative influence on downstream P loads. Using scenario simulations, we evaluate contribution from different sources. The results provide a detailed understanding of which sources dominate under varying conditions, enabling more targeted mitigation strategies.

### Project 2: Sensitivity analysis for phosphorus source attribution in an agricultural watershed using SWAT

Comprehensive sensitivity analysis to evaluate how key model parameters influence phosphorus source attribution in the Soil and Water Assessment Tool (SWAT). The analysis focused on major land-based P sources—including fertilizer, manure, and geogenic/legacy—within an intensively managed agricultural watershed. Using a combination of global sensitivity techniques and scenario-based simulations, to quantify the responsiveness of source-specific P loads to changes in parameter values controlling hydrology, erosion, and nutrient cycling.

### Project 3: Towards improved fertilizer application recommendations: Phosphorus field losses and use efficiency of different nutrient philosophies and practices

Fertilizer recommendation philosophies strongly influence phosphorus use efficiency (PUE) and the risk of P loss, yet their watershed-scale impacts remain poorly understood. This project will evaluate how different nutrient recommendation strategies influence PUE and P losses and crop productivity.

### Other projects

Oates, C. C., **Fajardo, H.**, Grieger, K., Obenour, D., Muenich, R., & Nelson, N. G. (2024). Effective Nutrient Management of Surface Waters in the United States Requires Expanded Water Quality Monitoring in Agriculturally Intensive Areas. ACS Environmental Au, 5(1), 1–11. [https://doi.org/https://doi.org/10.1021/acsenvironau.4c00060](https://doi.org/10.1021/acsenvironau.4c00060)

## 3. MSc: Soil Fertility (School of Plant, Environmental and Soil Sciences - Louisiana State University)

Theses Title: *Cover Cropping: Sensor-based estimations of biomass yield and nutrient uptake and its impact on sugarcane productivity* [DOI:10.31390/gradschool_theses.5634](https://repository.lsu.edu/gradschool_theses/5634/)

### Project 1: Use of NDVI for predicting cover crops biomass and nutrients uptake

This study evaluated the potential of remote sensing to estimate biomass and nutrient uptake of cool-season cover crops in sugarcane systems using NDVI derived from a ground-based GreenSeeker sensor and UAV-based multispectral imagery. NDVI measurements from both platforms were strongly correlated, with further improvements achieved by adjusting for growing-degree–related variables. GreenSeeker NDVI more effectively explained variation in biomass and nitrogen content, though both sensors exhibited saturation at high biomass levels. Strong linear relationships were observed for key macronutrients (N, K, P) and micronutrients (Mn, Cu), while others showed weaker correlations. Overall, the findings demonstrate that NDVI-based remote sensing is a promising and practical approach for estimating cover crop biomass and nutrient uptake.

### Project 2: Impact of planting method and rate of cover crops on soil nutrient levels and on sugarcane yield and quality components

In this project, planting method and seeding rate of cool-season cover crops were evaluated to on their influence on soil nutrient dynamics, as well as sugarcane yield and quality, across five Louisiana sites and two crop ages. Eight combinations of broadcast or drilled planting and varying seeding rates were tested using a legume–brassica cover crop mix, with measurements collected for cane yield, quality components, and soil macronutrients. Neither planting method nor seeding rate significantly affected sugarcane yield, quality parameters, cover crop nutrient removal, or soil nutrient concentrations, which varied mainly due to site conditions and sugarcane uptake. Although immediate effects on yield and soil nutrients were minimal, the study indicates that winter cover crops establish well in newly planted cane and may contribute more substantially to long-term nutrient management benefits in subsequent ratoon cycles.

## 2. Irrigation systems management consultant

## 1. BS: Agricultural Engineering (Universidad Mayor de San Andres - Bolivia)

### Project 1:

Modeling Quinoa Water and Nutrient Responses with the AquaCrop Model AquaCrop’s semi-quantitative soil fertility module reduces data requirements by using overall fertility levels rather than detailed nutrient inputs. When calibrated for quinoa in the Bolivian highlands, the model accurately simulated soil moisture, biomass, yield, and combined fertility–water stress responses.

Van Gaelen, H., Tsegay, A., Delbecque, N., Shrestha, N.K., Garcia, M.C., **Fajardo, H.**, Miranda, R., Vanuytrecht, E., Abrha, B., Diels, J., & Raes, D. (2014). A semi-quantitative approach for modelling crop response to soil fertility: evaluation of the AquaCrop procedure. The Journal of Agricultural Science, 153, 1218 - 1233. [doi:10.1017/S0021859614000872](https://doi.org/10.1017/S0021859614000872)

**Fajardo, H.**, García, M., Raes, D., & Van Gaelen, H. (2016). Validación Del Modelo Aquacrop Para Diferentes Niveles De Fertilidad En El Cultivo De Quinua En El Altiplano Boliviano. \[Validation Of The Aquacrop Model For Different Levels Of Fertilization On Quinoa Crop In The Bolivian Highlands·\] Revista Cintex, 21(2), 31-52. Retrieved from https://proxying.lib.ncsu.edu/index.php?url=https://www.proquest.com/scholarly-journals/validación-del-modelo-aquacrop-para-diferentes/docview/2676146745/se-2